// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SubSettestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void subSettest() {
    driver.get("http://localhost:8000/");
    driver.manage().window().setSize(new Dimension(1357, 817));
    driver.findElement(By.name("Email_List")).click();
    driver.findElement(By.name("Email_List")).sendKeys("kellywang@ucsb.edu");
    driver.findElement(By.name("Email_List")).sendKeys("kellywang@ucsb.edu");
    driver.findElement(By.name("Email_List")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".upload-btn-wrapper > .btn:nth-child(2)")).click();
    driver.findElement(By.id("file-upload")).sendKeys("/Users/KellyIzKewl/desktop/hello.png");
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_content")).click();
    driver.findElement(By.cssSelector(".ace_text-input")).sendKeys("        System.out.println("Hello World");\n\n");
    driver.findElement(By.id("format")).click();
    driver.findElement(By.id("compiler")).click();
    assertThat(driver.switchTo().alert().getText(), is("Hello World
    "));
    driver.findElement(By.id("DBInput")).click();
    assertThat(driver.switchTo().alert().getText(), is("File successfully saved to database!"));
    driver.findElement(By.id("DBOutput")).click();
    driver.findElement(By.cssSelector("li:nth-child(1)")).click();
    driver.findElement(By.id("export")).click();
  }
}
